name: "tagged-release"

on:
  push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]
    tags: 
      - "v*"

jobs:
  build:
    name: "build"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
          - goarch: amd64
            goos: darwin
          - goarch: amd64
            goos: windows
          - goarch: arm64
            goos: linux
          - goarch: arm64
            goos: darwin
          - goarch: arm64
            goos: windows
    
    steps:
      # ...
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -v ./...
      
      - name: GetVersion
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
      - name: Packaging...
        run: |
          find *|grep git_action_golang_test |grep -v ".tar"|xargs tar cvf git_action_golang_test-${{ matrix.goos }}-${{ matrix.goarch }}-${{ env.RELEASE_VERSION }}.tar 
          find * |grep git_action_golang_test|grep -v '.tar'|xargs rm 
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: git_action_golang_test-${{ matrix.goos }}-${{ matrix.goarch }}-${{ env.RELEASE_VERSION }}.tar # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: git_action_golang_test-${{ matrix.goos }}-${{ matrix.goarch }}-${{ env.RELEASE_VERSION }}.tar
      
#       - name: "release"
#         uses: "marvinpinto/action-automatic-releases@latest"
#         with:
#           repo_token: "${{ secrets.GITHUB_TOKEN }}"
#           automatic_release_tag: "${{ env.RELEASE_VERSION }}"
#           prerelease: false
#           files: |
#             git_action_golang_test-*.tar
      
        
        
  release: 
    name: "release"
    runs-on: "ubuntu-latest"
    needs: build
    steps:
      - name: GetVersion
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
      - name: Download artifact
        # You may pin to the exact commit or the version.
        # uses: aochmann/actions-download-artifact@5709392f11b5937bd316e52687ad87f7deced5f5
        uses: aochmann/actions-download-artifact@1.0.4
        with:
          # Artifact name (download all artifacts in not specified)
          name: git_action_golang_test-*-${{ env.RELEASE_VERSION }}.tar # optional
        
      - name: "release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.RELEASE_VERSION }}"
          prerelease: false
          files: |
            git_action_golang_test-*.tar

